// Generated by uniffi-bindgen-react-native
#include "wormhole-rn.h"
#include "generated/wormhole_core.hpp"

namespace wormholern {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeWormholeCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}