/* Generated by native/wormhole-mini/tools/genvectors. Do not edit. */
/* Source of truth: native/magic-wormhole/src/core/key.rs, transit.rs, */
/* transit/crypto.rs - the engine the Symbian client interoperates with. */
#ifndef WH_TEST_VECTORS_H
#define WH_TEST_VECTORS_H

static const char WH_V_APPID[] = "lothar.com/wormhole/text-or-file-xfer";

/* SHA-256 */
static const char WH_V_SHA256_EMPTY[] = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
static const char WH_V_SHA256_ABC[] = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";

/* derive_key = HKDF-SHA256(salt=none, ikm=key, info=purpose, 32 bytes) */
static const unsigned char WH_V_MAIN_KEY[32] = {
    0x58, 0x8b, 0xa9, 0xee, 0xf3, 0x53, 0x77, 0x8b, 0x07, 0x44, 0x13, 0xa0,
    0x14, 0x02, 0x05, 0xd9, 0x0d, 0x74, 0x79, 0xe3, 0x6e, 0x0d, 0xd4, 0xee,
    0x35, 0xbb, 0x72, 0x9d, 0x26, 0x13, 0x1e, 0xf1,
};
static const char WH_V_DERIVE_PURPOSE1[] = "835b5df80ce9ca46908e8524fb308649122cfbcefbeaa7e65061c6ef08ee1b2a";
static const char WH_V_VERIFIER[] = "5dc3da0c2cc7975c3b5e266aeab1e9c792c8bcbe3a28595b7ba5a8c756b06264";

/* derive_phase_key(side, key, phase) */
static const char WH_V_SIDE[] = "3f0ab1c2d9";
static const char WH_V_PHASE_KEY_PAKE[] = "db20af6a8b11ee164e4cbabed27ba74bcacc153ab7d1faa6d8f0e09223de0261";
static const char WH_V_PHASE_KEY_VERSION[] = "5d955f752cfe6ea117bb3a9c7d3df56354c230604a5af7cd51edbb565217ab2d";
static const char WH_V_PHASE_KEY_0[] = "10f6b3b199347b658411f7187b2b10136fb4c3df5019cbf9496d8d9de1a93260";

/* transit key and its subkeys, plus the literal handshake lines */
static const char WH_V_TRANSIT_KEY[] = "a7d95312e88d9096043efe939e4f0059b76ed41887fc6b80ae242b9fcd65647b";
static const char WH_V_TRANSIT_RELAY_TOKEN[] = "2c388a633c39f493c20d90cada0bf53b265f158588d49212b077f44f3ac8904a";
static const char WH_V_TRANSIT_SENDER[] = "4803905e8b679e37488f1edeced1cdab80e52819680e6fe3b23fe25e905fd680";
static const char WH_V_TRANSIT_RECEIVER[] = "8953a84261410a90f14470fea4dac24f2bc545ee68d15bbea137a80dbb6de98e";
static const char WH_V_TRANSIT_RECORD_SENDER_KEY[] = "6ec04ce48d625af6b3610ad48218bb37146ac4664735acbc0360d84f32c7b6b1";
static const char WH_V_TRANSIT_RECORD_RECEIVER_KEY[] = "ec866ef0865b37ac35d29e135979af47a2c18cabd946b44150b0475edb4ef32a";
static const char WH_V_RELAY_LINE[] = "please relay 2c388a633c39f493c20d90cada0bf53b265f158588d49212b077f44f3ac8904a for side 3f0ab1c2d9\n";
static const char WH_V_TRANSIT_SENDER_LINE[] = "transit sender 4803905e8b679e37488f1edeced1cdab80e52819680e6fe3b23fe25e905fd680 ready\n\n";
static const char WH_V_TRANSIT_RECEIVER_LINE[] = "transit receiver 8953a84261410a90f14470fea4dac24f2bc545ee68d15bbea137a80dbb6de98e ready\n\n";

/* XSalsa20-Poly1305, wire format is nonce(24) || ciphertext */
static const unsigned char WH_V_SB_KEY[32] = {
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
};
static const unsigned char WH_V_SB_NONCE[24] = {
    0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09,
    0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09,
};
static const unsigned char WH_V_SB_PLAINTEXT[22] = {
    0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x20, 0x67, 0x65, 0x6d, 0x73, 0x20,
    0x6f, 0x6e, 0x20, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x61, 0x6e,
};
static const unsigned char WH_V_SB_WIRE[62] = {
    0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09,
    0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09, 0x09,
    0x7b, 0xe8, 0x17, 0xcf, 0x5e, 0x66, 0x94, 0x97, 0x62, 0xdb, 0xc6, 0x42,
    0xb8, 0x85, 0xb4, 0xe6, 0xfc, 0x25, 0x61, 0x82, 0x5e, 0x3d, 0x12, 0x8b,
    0x61, 0x19, 0x61, 0xc8, 0xc5, 0x5a, 0x95, 0x21, 0x19, 0xf0, 0xec, 0x5b,
    0x35, 0x21,
};

#endif /* WH_TEST_VECTORS_H */
