#!/usr/bin/env python3
"""Generates tests/vectors/inflate_vectors.h.

Compresses known payloads with zlib and embeds the compressed bytes plus the
expected length and CRC-32 of the original. Checking a CRC rather than the
bytes keeps the header small even where the payload is 100 KB, which matters
because the interesting cases - window wrap, long back-references - only
appear well past 32 KB.

Run: python3 tools/geninflate.py > tests/vectors/inflate_vectors.h
"""
import sys
import zlib


def payloads():
    yield "empty", b"", 6
    yield "short", b"hello world", 6
    # Highly repetitive: long matches, small distances.
    yield "repetitive", b"ab" * 50000, 6
    # Poorly compressible: forces dynamic or stored blocks.
    rnd = bytearray()
    state = 12345
    for _ in range(100000):
        state = (1103515245 * state + 12345) & 0x7FFFFFFF
        rnd.append((state >> 16) & 0xFF)
    yield "incompressible", bytes(rnd), 6
    # A match at nearly the maximum distance, which is what exercises the
    # 32 KB window and the wrap in the circular buffer.
    far = b"MARKER-" + bytes(40000) + b"MARKER-"
    yield "far_match", far, 9
    # Level 0 emits stored blocks, a separate code path entirely.
    yield "stored", b"stored blocks are a different branch" * 100, 0
    # Text with structure, the ordinary case.
    yield "text", (b"the quick brown fox jumps over the lazy dog. " * 500), 6


def emit_bytes(name, data):
    print("static const unsigned char %s[%d] = {" % (name, len(data)))
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        print("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
    print("};")


def main():
    out = sys.stdout
    out.write("/* Generated by native/wormhole-mini/tools/geninflate.py. */\n")
    out.write("/* Compressed with zlib; verified by length and CRC-32. */\n")
    out.write("#ifndef WH_INFLATE_VECTORS_H\n#define WH_INFLATE_VECTORS_H\n\n")

    names = []
    for name, data, level in payloads():
        comp = zlib.compressobj(level, zlib.DEFLATED, -15)
        blob = comp.compress(data) + comp.flush()
        if len(blob) == 0:
            # An empty payload still needs a final empty block.
            blob = zlib.compress(data, level)[2:-4]
        emit_bytes("WH_IV_%s_DEFLATED" % name.upper(), blob)
        print("#define WH_IV_%s_LEN %dUL" % (name.upper(), len(data)))
        print("#define WH_IV_%s_CRC 0x%08xUL\n" % (name.upper(), zlib.crc32(data) & 0xFFFFFFFF))
        names.append(name)

    print("/* A stream that is not valid deflate, for the rejection path. */")
    emit_bytes("WH_IV_CORRUPT", bytes([0xFF] * 32))
    print()

    print("typedef struct {")
    print("    const char *name;")
    print("    const unsigned char *data;")
    print("    unsigned long size;")
    print("    unsigned long expect_len;")
    print("    unsigned long expect_crc;")
    print("} wh_iv_case;\n")
    print("static const wh_iv_case WH_IV_CASES[] = {")
    for name in names:
        u = name.upper()
        print("    { \"%s\", WH_IV_%s_DEFLATED, sizeof(WH_IV_%s_DEFLATED),"
              " WH_IV_%s_LEN, WH_IV_%s_CRC }," % (name, u, u, u, u))
    print("};\n")
    print("#endif /* WH_INFLATE_VECTORS_H */")


if __name__ == "__main__":
    main()
