#!/usr/bin/env python3
"""Generates src/wordlist.c from the engine's own PGP wordlist.

Source of truth: native/magic-wormhole/src/core/pgpwords.json, loaded by
core/wordlist.rs. Each entry maps a byte to [odd_word, even_word]; a
two-word code takes its first word from the even list and its second from
the odd list (Wordlist::choose_words cycles [even, odd]).

Run: python3 tools/genwordlist.py > src/wordlist.c
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "magic-wormhole", "src", "core", "pgpwords.json")


def main():
    with open(SRC) as f:
        raw = json.load(f)
    if len(raw) != 256:
        sys.exit("expected 256 entries, found %d" % len(raw))

    odd = [None] * 256
    even = [None] * 256
    for key, pair in raw.items():
        i = int(key, 16)
        odd[i] = pair[0].lower()
        even[i] = pair[1].lower()
    if any(w is None for w in odd + even):
        sys.exit("wordlist has holes")

    out = sys.stdout.write
    out("/* Generated by tools/genwordlist.py. Do not edit. */\n")
    out("/* Source: native/magic-wormhole/src/core/pgpwords.json - the same\n")
    out(" * list the engine uses, so codes generated on the phone look like\n")
    out(" * codes from every other wormhole client. */\n")
    out('#include "wordlist.h"\n\n')

    for name, words in (("wh_even_words", even), ("wh_odd_words", odd)):
        out("const char *const %s[WH_WORDLIST_SIZE] = {\n" % name)
        line = "   "
        for w in words:
            piece = ' "%s",' % w
            if len(line) + len(piece) > 78:
                out(line + "\n")
                line = "   "
            line += piece
        if line.strip():
            out(line + "\n")
        out("};\n\n")


if __name__ == "__main__":
    main()
