#!/usr/bin/env python3
"""Generates tests/vectors/zip_vectors.h - real archives built by zipfile.

Covers what a folder transfer actually produces (deflated entries, nested
paths, empty directories) plus the shapes that break naive readers: stored
entries, an archive comment so the end record is not at the end of the file,
and a file large enough to cross the 32 KB inflate window.

Run: python3 tools/genzip.py > tests/vectors/zip_vectors.h
"""
import io
import sys
import zipfile
import zlib


def build(entries, comment=None, method=zipfile.ZIP_DEFLATED):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", method) as z:
        for name, data in entries:
            if data is None:
                z.writestr(name, b"")      # directory entry, name ends in /
            else:
                z.writestr(name, data)
        if comment:
            z.comment = comment
    return buf.getvalue()


def cases():
    simple = [
        ("notes.txt", b"a short note"),
        ("photos/one.jpg", b"\xff\xd8\xff" + bytes(range(256)) * 4),
        ("photos/two.jpg", b"\xff\xd8\xff" + bytes(range(255, -1, -1)) * 4),
        ("empty/", None),
    ]
    yield "folder", build(simple)
    yield "stored", build(simple, method=zipfile.ZIP_STORED)
    # A comment pushes the end record away from the end of the file.
    yield "commented", build(simple, comment=b"x" * 900)
    # Larger than the inflate window, and compressible so the vector stays small.
    yield "big", build([("big.bin", (b"portalgems " * 10000))])
    # Deep nesting, which is where a path join goes wrong.
    yield "nested", build([("a/b/c/d/deep.txt", b"deep"), ("a/b/", None)])


def main():
    print("/* Generated by native/wormhole-mini/tools/genzip.py. */")
    print("#ifndef WH_ZIP_VECTORS_H")
    print("#define WH_ZIP_VECTORS_H\n")
    print("typedef struct {")
    print("    const char *name;")
    print("    unsigned long size;")
    print("    unsigned long crc;")
    print("    int is_dir;")
    print("} wh_zv_entry;\n")
    print("typedef struct {")
    print("    const char *name;")
    print("    const unsigned char *data;")
    print("    unsigned long size;")
    print("    const wh_zv_entry *entries;")
    print("    int count;")
    print("} wh_zv_case;\n")

    names = []
    for name, blob in cases():
        u = name.upper()
        print("static const unsigned char WH_ZV_%s_DATA[%d] = {" % (u, len(blob)))
        for i in range(0, len(blob), 12):
            print("    " + ", ".join("0x%02x" % b for b in blob[i:i + 12]) + ",")
        print("};")

        with zipfile.ZipFile(io.BytesIO(blob)) as z:
            infos = z.infolist()
            print("static const wh_zv_entry WH_ZV_%s_ENTRIES[%d] = {" % (u, len(infos)))
            for info in infos:
                data = z.read(info.filename)
                is_dir = 1 if info.filename.endswith("/") else 0
                print('    { "%s", %dUL, 0x%08xUL, %d },'
                      % (info.filename, len(data),
                         zlib.crc32(data) & 0xFFFFFFFF, is_dir))
            print("};\n")
        names.append((name, u))

    print("static const wh_zv_case WH_ZV_CASES[] = {")
    for name, u in names:
        print('    { "%s", WH_ZV_%s_DATA, sizeof(WH_ZV_%s_DATA),'
              ' WH_ZV_%s_ENTRIES,'
              ' (int)(sizeof(WH_ZV_%s_ENTRIES)/sizeof(wh_zv_entry)) },'
              % (name, u, u, u, u))
    print("};\n")
    print("#endif /* WH_ZIP_VECTORS_H */")


if __name__ == "__main__":
    main()
