//! Generates `native/wormhole-mini/tests/vectors/vectors.h`.
//!
//! Mirrors `native/magic-wormhole/src/core/key.rs` exactly, using the same
//! crate versions the engine depends on, so the C client in
//! `native/wormhole-mini` can be validated offline against the behaviour of
//! the Rust engine it has to interoperate with.
//!
//! Run: `cargo run --manifest-path native/wormhole-mini/tools/genvectors/Cargo.toml \
//!        > native/wormhole-mini/tests/vectors/vectors.h`

use crypto_secretbox::{
    aead::{Aead, KeyInit, generic_array::GenericArray},
    XSalsa20Poly1305,
};
use hkdf::Hkdf;
use sha2::{Digest, Sha256};

/// `key.rs::sha256_digest`
fn sha256(input: &[u8]) -> [u8; 32] {
    let mut h = Sha256::default();
    h.update(input);
    h.finalize().into()
}

/// `key.rs::derive_key` - HKDF-SHA256, no salt, 32 bytes out.
fn derive_key(key: &[u8], purpose: &[u8]) -> [u8; 32] {
    let hk = Hkdf::<Sha256>::new(None, key);
    let mut out = [0u8; 32];
    hk.expand(purpose, &mut out).unwrap();
    out
}

/// `key.rs::derive_phase_key` - note the digests go in as raw bytes, not hex.
fn derive_phase_key(side: &str, key: &[u8], phase: &str) -> [u8; 32] {
    let mut purpose = b"wormhole:phase:".to_vec();
    purpose.extend_from_slice(&sha256(side.as_bytes()));
    purpose.extend_from_slice(&sha256(phase.as_bytes()));
    derive_key(key, &purpose)
}

fn emit_bytes(name: &str, bytes: &[u8]) {
    println!("static const unsigned char {name}[{}] = {{", bytes.len());
    for chunk in bytes.chunks(12) {
        let line: Vec<String> = chunk.iter().map(|b| format!("0x{b:02x}")).collect();
        println!("    {},", line.join(", "));
    }
    println!("}};");
}

fn emit_hex(name: &str, bytes: &[u8]) {
    println!("static const char {name}[] = \"{}\";", hex::encode(bytes));
}

fn emit_str(name: &str, s: &str) {
    println!("static const char {name}[] = \"{}\";", s.escape_default());
}

fn main() {
    // Same app id as native/magic-wormhole/src/transfer.rs:47.
    const APPID: &str = "lothar.com/wormhole/text-or-file-xfer";

    println!("/* Generated by native/wormhole-mini/tools/genvectors. Do not edit. */");
    println!("/* Source of truth: native/magic-wormhole/src/core/key.rs, transit.rs, */");
    println!("/* transit/crypto.rs - the engine the Symbian client interoperates with. */");
    println!("#ifndef WH_TEST_VECTORS_H");
    println!("#define WH_TEST_VECTORS_H\n");
    emit_str("WH_V_APPID", APPID);
    println!();

    // --- SHA-256 ---------------------------------------------------------
    println!("/* SHA-256 */");
    emit_hex("WH_V_SHA256_EMPTY", &sha256(b""));
    emit_hex("WH_V_SHA256_ABC", &sha256(b"abc"));
    println!();

    // --- HKDF / derive_key ----------------------------------------------
    // The first pair is the engine's own committed unit-test vector
    // (key.rs::test_derive_key), so a mismatch here means this generator has
    // drifted from the engine, not that the C code is wrong.
    println!("/* derive_key = HKDF-SHA256(salt=none, ikm=key, info=purpose, 32 bytes) */");
    let main_key =
        hex::decode("588ba9eef353778b074413a0140205d90d7479e36e0dd4ee35bb729d26131ef1").unwrap();
    emit_bytes("WH_V_MAIN_KEY", &main_key);
    emit_hex("WH_V_DERIVE_PURPOSE1", &derive_key(&main_key, b"purpose1"));
    assert_eq!(
        hex::encode(derive_key(&main_key, b"purpose1")),
        "835b5df80ce9ca46908e8524fb308649122cfbcefbeaa7e65061c6ef08ee1b2a",
        "generator drifted from native/magic-wormhole/src/core/key.rs test_derive_key"
    );
    emit_hex("WH_V_VERIFIER", &derive_key(&main_key, b"wormhole:verifier"));
    println!();

    // --- phase keys ------------------------------------------------------
    println!("/* derive_phase_key(side, key, phase) */");
    emit_str("WH_V_SIDE", "3f0ab1c2d9");
    emit_hex(
        "WH_V_PHASE_KEY_PAKE",
        &derive_phase_key("3f0ab1c2d9", &main_key, "pake"),
    );
    emit_hex(
        "WH_V_PHASE_KEY_VERSION",
        &derive_phase_key("3f0ab1c2d9", &main_key, "version"),
    );
    emit_hex(
        "WH_V_PHASE_KEY_0",
        &derive_phase_key("3f0ab1c2d9", &main_key, "0"),
    );
    println!();

    // --- transit ---------------------------------------------------------
    println!("/* transit key and its subkeys, plus the literal handshake lines */");
    let transit_key = derive_key(&main_key, format!("{APPID}/transit-key").as_bytes());
    emit_hex("WH_V_TRANSIT_KEY", &transit_key);
    let relay_token = derive_key(&transit_key, b"transit_relay_token");
    let sender = derive_key(&transit_key, b"transit_sender");
    let receiver = derive_key(&transit_key, b"transit_receiver");
    emit_hex("WH_V_TRANSIT_RELAY_TOKEN", &relay_token);
    emit_hex("WH_V_TRANSIT_SENDER", &sender);
    emit_hex("WH_V_TRANSIT_RECEIVER", &receiver);
    emit_hex(
        "WH_V_TRANSIT_RECORD_SENDER_KEY",
        &derive_key(&transit_key, b"transit_record_sender_key"),
    );
    emit_hex(
        "WH_V_TRANSIT_RECORD_RECEIVER_KEY",
        &derive_key(&transit_key, b"transit_record_receiver_key"),
    );
    // Exact bytes on the wire. The relay line ends with one \n; the two
    // handshake lines end with \n\n and are 89 and 89 bytes respectively,
    // with the leader following its line with "go\n" (transit/crypto.rs).
    emit_str(
        "WH_V_RELAY_LINE",
        &format!("please relay {} for side 3f0ab1c2d9\n", hex::encode(relay_token)),
    );
    let sender_line = format!("transit sender {} ready\n\n", hex::encode(sender));
    let receiver_line = format!("transit receiver {} ready\n\n", hex::encode(receiver));
    // transit/crypto.rs asserts these exact lengths: the leader expects an
    // 89-byte receiver line, the follower expects the 87-byte sender line
    // followed by "go\n" for 90 bytes total. The two lines differ in length
    // because "receiver" is two characters longer than "sender".
    assert_eq!(sender_line.len(), 87);
    assert_eq!(receiver_line.len(), 89);
    assert_eq!(sender_line.len() + 3, 90);
    emit_str("WH_V_TRANSIT_SENDER_LINE", &sender_line);
    emit_str("WH_V_TRANSIT_RECEIVER_LINE", &receiver_line);
    println!();

    // --- secretbox -------------------------------------------------------
    println!("/* XSalsa20-Poly1305, wire format is nonce(24) || ciphertext */");
    let sb_key = [7u8; 32];
    let nonce = [9u8; 24];
    let plaintext = b"portal gems on symbian";
    let cipher = XSalsa20Poly1305::new(GenericArray::from_slice(&sb_key));
    let ct = cipher
        .encrypt(GenericArray::from_slice(&nonce), plaintext.as_ref())
        .unwrap();
    let mut wire = nonce.to_vec();
    wire.extend_from_slice(&ct);
    emit_bytes("WH_V_SB_KEY", &sb_key);
    emit_bytes("WH_V_SB_NONCE", &nonce);
    emit_bytes("WH_V_SB_PLAINTEXT", plaintext);
    emit_bytes("WH_V_SB_WIRE", &wire);
    println!();

    println!("#endif /* WH_TEST_VECTORS_H */");
}
